version: "3.7"

services:
    currency_scrapper_database:
        environment:
            - POSTGRES_DB=currency_scrapper_database
            - POSTGRES_HOST=localhost
            - POSTGRES_USER=currency_scrapper_user
            - POSTGRES_PASSWORD=currency_scrapper_password
        container_name: currency_scrapper_database
        image: postgres:alpine
        networks:
            - currency_scrapper
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 30s
            retries: 3

networks:
    currency_scrapper:
        name: currency_scrapper

